### ISSUE TITLE
Problem with the database

### ISSUE THREAD

**Issue by Listlessness** [thomasperge/RPG-Discord-Bot#1]
node:events:368
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read properties of null (reading 'numberPlayer')
    at /home/runner/RPG-Discord-Bot/commands/createplayer.js:66:13
    at /home/runner/RPG-Discord-Bot/node_modules/mongoose/lib/model.js:5074:18
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
Emitted 'error' event on Function instance at:
    at /home/runner/RPG-Discord-Bot/node_modules/mongoose/lib/model.js:5076:15
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
exit status 1

**Comment by thomasperge** [comment]
Hi, indeed you have this error, because you must remove the comments on the
creation of the model 'STATS' (the variable statsBot in the file
createplayer.js) and put it before the creation of the model 'PLAYER'. You
launch the bot, you type the command '<prefix>start', and then you put in
comment the model 'STATS' not to create several times the statics of the
bot.

**Comment by XenonDevZ** [comment]
I also have this issue and I dont get your point, can you elaborate
